# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'facebook-godot' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  # Pods for facebook-godot

end
